
-- 2006/04/29 为越南版修改师傅收徒弟限制，七天只能收五个。   by peres

TTKID_APPRENTICE_FLAG = 20 --拜师请求标识
TTKID_RECRUIT_FLAG = 21 --收徒请求标识
TTKID_SELF_LILIAN_FLAG = 22 --徒弟请求复命标识
TTKID_MASTER_LILIAN_FLAG = 23 --师父请求查看标识
TTKID_APPRENTICE_CHUSHI = 24 --徒弟出师请求标识
TTKID_MASTER_CHUSHI = 25 --师父要求出师请求标识

TKID_APPLY_JOIN_LEAGUE = 1400
TKID_APPLY_GRADUATE = 1401
TKID_MASTER_COUNT = 1402 --拜师总数
TKID_APPRENTICE_COUNT = 1403 --收徒弟总数
TKID_ENTER_LEVEL = 1404 --拜师时的等级
TKID_CHUSHI_MASTER_BONUS = 1405  --出师时师父的奖励
TKID_CHUSHI_APPRENTICE_BONUS = 1406  --出师师徒弟的奖励
TKID_CHUSHI_DICHUAN_BONUS = 1407 --嫡传弟子额外奖励
TKID_CHUSHI_ZHIXI_BONUS = 1408 --直系弟子额外奖励
TKID_DICHUAN_APPRENTICE_COUNT = 1409 --嫡传弟子数
TKID_ZHIXI_APPRENTICE_COUNT = 1410 --直系弟子数
TKID_NORMAL_APPRENTICE_COUNT = 1411 --普通弟子数

TKID_LAST_SHITU_OPERATION = 1412 --上一次对League操作的ID
TKID_LAST_SHITU_DATA1=	1413
TKID_LAST_SHITU_DATA2=	1414
TKID_MASTER_BREAK_TIME = 1415 --最后一次师父解除师徒关系的时间
TKID_APPRENTICE_BREAK_TIME = 1416 --最后一次徒弟解除师徒关系的时间

TKID_GOLD_APPRENTICE = 1399 -- 黄金徒弟(0 - 普通，1 - 未发过拜师公告，2 - 发过拜师公告)

CONST_BREAKSHITU_PROTECTEDTIME = 24*60*60 -- 解除师徒关系前的保护时间 (秒)
CONST_SHITU_TU_TITLEID = 30	-- 徒弟的称号

CONST_BONUS_COUNT_APPRENTICE = 2
CONST_LEAGUEJOB_MASTER = 1
CONST_LEAGUEJOB_APPRENTICE = 2
CONST_LEAGUETYPE_SHITU = 1
CONST_DEGREE_MASTER = CONST_LEAGUEJOB_MASTER
CONST_DEGREE_APPRENTICE = CONST_LEAGUEJOB_APPRENTICE
CONST_DEGREE_PREAPPRENTICE = 3
CONST_DEGREE_PREMASTER = 4


CONST_OPER_JOINSHITU = 1;
CONST_OPER_GRADUATE= 2;
CONST_OPER_LEAVESHITU = 3;


TKID_SELF_LILIAN = 1450 --个人历练的列表
TKID_MASTER_LILIAN = 1460 --在师父名下的历练列表
TKID_BONUS_LILIAN = 1470 --历练的发奖列表

ID_SHITU_LIMIT_DATE = 2417  -- 越南师徒系统记录限制日期
ID_SHITU_LIMIT_NUM  = 2418  -- 越南师徒系统记录限制数量

CONST_SHITU_LIMIT_TIME    = 60 * 60 * 24 * 7  -- 七天限制的秒数总数

CONST_LILIAN_MEM_WIDTH = 4

CONST_LLITEM_JOINPARTY = 1
CONST_LLITEM_YESOUTASK = 2
CONST_LLITEM_ZHENGPAI20 = 3
CONST_LLITEM_ZHONGLI20 = 4
CONST_LLITEM_XIEPAI20 = 5
CONST_LLITEM_ZHENGPAI30 = 6
CONST_LLITEM_ZHONGLI30 = 7
CONST_LLITEM_XIEPAI30 = 8
CONST_LLITEM_ZHENGPAI40 = 9
CONST_LLITEM_ZHONGLI40 = 10
CONST_LLITEM_XIEPAI40 = 11
CONST_LLITEM_ZHENGPAI50 = 12
CONST_LLITEM_ZHONGLI50 = 13
CONST_LLITEM_XIEPAI50 = 14
CONST_LLITEM_ZHENGPAI60 = 15
CONST_LLITEM_ZHONGLI60 = 16
CONST_LLITEM_XIEPAI60 = 17
CONST_LLITEM_SONGJIN = 18
CONST_LLITEM_GETSKILL60 = 19
CONST_LLITEM_LEVEL65 = 20
CONST_LLITEM_LEVEL70 = 21
CONST_LLITEM_LEVEL75 = 22
CONST_LLITEM_LEVEL76 = 23
CONST_LLITEM_LEVEL77 = 24
CONST_LLITEM_LEVEL78 = 25
CONST_LLITEM_LEVEL79 = 26
CONST_LLITEM_LEVEL80 = 27
CONST_LLITEM_SKILL10UP5 = 28
CONST_LLITEM_SKILL10UP15 = 29
CONST_LLITEM_GETSKILL30 = 30
CONST_LLITEM_GETSKILL40 = 31
CONST_LLITEM_GETSKILL50 = 32
CONST_LLITEM_SKILL60UP3 = 33
CONST_LLITEM_JOINTONG = 34
CONST_LLITEM_SHENGWANG = 35
CONST_LLITEM_SHANHESHEJI = 36
LILIAN_ITEM = {
	[CONST_LLITEM_JOINPARTY] = "拜入一个门派",
	[CONST_LLITEM_YESOUTASK] = "连续成功完成10次以上野叟任务",
	[CONST_LLITEM_ZHENGPAI20] = "完成正派20级主线任务",
	[CONST_LLITEM_ZHONGLI20] = "完成中立20级主线任务",
	[CONST_LLITEM_XIEPAI20] = "完成邪派20级主线任务",
	[CONST_LLITEM_ZHENGPAI30] = "完成正派30级主线任务",
	[CONST_LLITEM_ZHONGLI30] = "完成中立30级主线任务",
	[CONST_LLITEM_XIEPAI30] = "完成邪派30级主线任务",
	[CONST_LLITEM_ZHENGPAI40] = "完成正派40级主线任务",
	[CONST_LLITEM_ZHONGLI40] = "完成中立40级主线任务",
	[CONST_LLITEM_XIEPAI40] = "完成邪派40级主线任务",
	[CONST_LLITEM_ZHENGPAI50] = "完成正派50级主线任务",
	[CONST_LLITEM_ZHONGLI50] = "完成中立50级主线任务",
	[CONST_LLITEM_XIEPAI50] = "完成邪派50级主线任务",
	[CONST_LLITEM_ZHENGPAI60] = "完成正派60级主线任务",
	[CONST_LLITEM_ZHONGLI60] = "完成中立60级主线任务",
	[CONST_LLITEM_XIEPAI60] = "完成邪派60级主线任务",
	[CONST_LLITEM_SONGJIN] = "获得1000分以上宋金积分",
	[CONST_LLITEM_GETSKILL60] = "习得本门60级武功",
	[CONST_LLITEM_LEVEL65] = "等级提升至65级以上",
	[CONST_LLITEM_LEVEL70] = "等级提升至70级以上",
	[CONST_LLITEM_LEVEL75] = "等级提升至75级以上",
	[CONST_LLITEM_LEVEL76] = "等级提升至76级以上",
	[CONST_LLITEM_LEVEL77] = "等级提升至77级以上",
	[CONST_LLITEM_LEVEL78] = "等级提升至78级以上",
	[CONST_LLITEM_LEVEL79] = "等级提升至79级以上",
	[CONST_LLITEM_LEVEL80] = "等级提升至80级以上",
	[CONST_LLITEM_SKILL10UP5] = "本门10级武功提升到5级以上",
	[CONST_LLITEM_SKILL10UP15] = "本门10级武功提升到15级以上",
	[CONST_LLITEM_GETSKILL30] = "习得本门30级武功",
	[CONST_LLITEM_GETSKILL40] = "习得本门40级武功",
	[CONST_LLITEM_GETSKILL50] = "习得本门50级武功",
	[CONST_LLITEM_SKILL60UP3] = "本门60级武功提升到3级以上",
	[CONST_LLITEM_JOINTONG] = "加入到一个帮派",
	[CONST_LLITEM_SHENGWANG] = "获得200点以上的声望",
	[CONST_LLITEM_SHANHESHEJI] = "获得500个以上的山河社稷图残片",
}

CONST_PARTY_SHAOLIN = 0
CONST_PARTY_TIANWANG = 1
CONST_PARTY_TANGMEN = 2
CONST_PARTY_WUDU = 3
CONST_PARTY_EMEI = 4
CONST_PARTY_CUIYAN = 5
CONST_PARTY_GAIBANG = 6
CONST_PARTY_TIANREN = 7
CONST_PARTY_WUDANG = 8
CONST_PARTY_KUNLUN = 9
CONST_PARTY_NOT = -1
CONST_SKILL_LUOHANZHEN = 16	--罗汉阵
CONST_SKILL_SHIZIHOU = 20	--狮子吼
CONST_SKILL_LONGZHAOHUZHUA = 271	--龙爪虎抓
CONST_SKILL_HENGSAOLIUHE = 11	--横扫六合
CONST_SKILL_MOHEWULIANG = 19	--摩诃无量
CONST_SKILL_YIJINJING = 21	--易筋经
CONST_SKILL_POFENGZHAN = 37	--泼风斩
CONST_SKILL_YANGGUANSANDIE = 35	--阳关三叠
CONST_SKILL_XINGYUNJUE = 31	--行云诀
CONST_SKILL_DUANHUNCI = 40	--断魂刺
CONST_SKILL_JINZHONGZHAO = 42	--金钟罩
CONST_SKILL_TIANWANGZHANYI = 36	--天王战意
CONST_SKILL_WUXINZHAN= 32	--无心斩
CONST_SKILL_XUEZHANBAFANG = 41	--血战八方
CONST_SKILL_CHENGLONGJUE = 324	--乘龙诀
CONST_SKILL_ZHUIXINJIAN = 50	--追心箭
CONST_SKILL_MANTIANHUAYU = 54	--漫天花雨
CONST_SKILL_DUOHUNBIAO = 47	--夺魂镖
CONST_SKILL_CHUANXINCI = 343	--穿心刺
CONST_SKILL_HANBINGCI = 345	---寒冰刺
CONST_SKILL_LEIJISHU = 349	--雷击术
CONST_SKILL_XINYAN = 48	--心眼
CONST_SKILL_XIAOLIFEIDAO = 249	--小李飞刀
CONST_SKILL_TIANLUODIWANG = 58	--天罗地网
CONST_SKILL_SANHUABIAO = 341	--散花镖
CONST_SKILL_YOUMINGKULOU = 68	--幽冥骷髅
CONST_SKILL_BAIDUCHUANXIN = 384	--百毒穿心
CONST_SKILL_BINGLANXUANJING = 64	--冰蓝玄晶
CONST_SKILL_WUXINGGU = 69	--无形蛊
CONST_SKILL_CHUANYIPOJIA = 356	--穿衣破甲
CONST_SKILL_WANGUSHIXIN = 73	--万蛊蚀心
CONST_SKILL_CHUANXINDUCI = 72	--穿心毒刺
CONST_SKILL_WUDUQIJING = 75	--五毒奇经
CONST_SKILL_TIANGANGDISHA = 71	--天罡地煞
CONST_SKILL_ZHUHAQINGMING = 74	--朱蛤青冥
CONST_SKILL_TUICHUANGWANGYUE = 385	--推窗望月
CONST_SKILL_SIXIANGTONGGUI = 82	--四象同归
CONST_SKILL_MENGDIE = 89	--梦蝶
CONST_SKILL_LIUSHUI = 86	--流水
CONST_SKILL_FOXINCIYOU = 92	--佛心慈佑
CONST_SKILL_FOFAWUBIAN = 252	--佛法无边
CONST_SKILL_BUMIEBUJUE = 88	--不灭不绝
CONST_SKILL_FOGUANGPUZHAO = 91	--佛光普照
CONST_SKILL_QINGXINFANCHANG = 282	--清音梵唱
CONST_SKILL_YUDALIHUA = 105	--雨打梨花
CONST_SKILL_FUYUNSANXUE = 113	--浮云散雪
CONST_SKILL_TUTIHANBING = 100	--护体寒冰
CONST_SKILL_XUEYING = 109	--雪影
CONST_SKILL_BINGGUXUEXIN = 114	--冰骨雪心
CONST_SKILL_MUYELIUXING = 108	--牧野流星
CONST_SKILL_BIHAICHAOSHENG = 111	--碧海潮生
CONST_SKILL_XIANGLONGZHANG = 274	--降龙掌
CONST_SKILL_DAGOUBANG = 124	--打狗阵
CONST_SKILL_HUABULIUSHOU = 277	--滑不留手
CONST_SKILL_KANGLONGYOUHUI = 128	--亢龙有悔
CONST_SKILL_BANGDAEGOU = 125	--棒打恶狗
CONST_SKILL_ZUIDIEKUANGWU = 130	--醉蝶狂舞
CONST_SKILL_XIAOYAOGONG = 360	--逍遥功
CONST_SKILL_LIEHONGQINGTIAN = 141	--烈火情天
CONST_SKILL_TUISHANTIANHAI = 138	--推山填海
CONST_SKILL_FEIHONGWUJI = 140	--飞鸿无迹
CONST_SKILL_BEISUQINGFENG = 364	--悲酥清风
CONST_SKILL_LIMODUOPO = 143	--厉魔夺魂
CONST_SKILL_TIANMOJIETIE = 150	--天魔解体
CONST_SKILL_TOUTIANHUANRI = 142	--偷天换日
CONST_SKILL_MOYANQISHA = 148	--魔焰七杀
CONST_SKILL_BOJIERFU = 164	--剥及而复
CONST_SKILL_JIANFEIJINGTIAN = 158	--剑飞惊天
CONST_SKILL_TIYUNZONG = 160	--梯云纵
CONST_SKILL_ZUOWANGWUWO = 157	--坐忘无我
CONST_SKILL_TAIJISHENGONG = 166	--太极神功
CONST_SKILL_WUWOWUJIAN = 165	--无我无剑
CONST_SKILL_SANHUANTAOYUE = 267	--三环套月
CONST_SKILL_YIQISANQING = 178	--一气三清
CONST_SKILL_TIANJIXUNLEI = 172	--天际迅雷
CONST_SKILL_BEIMINGDAOHAI = 393	--北冥到海
CONST_SKILL_TIANQINGDIZUO = 173	--天清地浊
CONST_SKILL_QIHANAOXUE = 175	--欺寒傲雪
CONST_SKILL_QIXINFU = 181	--弃心符
CONST_SKILL_KUANGFENGZHOUDIAN = 176	--狂风骤电
CONST_SKILL_MIZONGHUANGYING = 90	--迷踪幻影
CONST_SKILL_SHUANGAOKUNLUN = 275	--霜傲昆仑
CONST_SKILL_WULEIZHENGFA = 182	--五雷正法
CONST_SKILL_SHAOLINQUANFA = 8	--少林拳法
CONST_SKILL_SHAOLINGUNFA = 4	--少林棍法
CONST_SKILL_SHAOLINDAOFA = 6	--少林刀法
CONST_SKILL_TIANWANGCHUIFA = 26	--天王锤法
CONST_SKILL_TIANWANGQIANGFA = 23	--天王枪法
CONST_SKILL_TIANWANGDAOFA = 24	--天王刀法
CONST_SKILL_TANGMENANQI = 43	--唐门暗器
CONST_SKILL_DIYANHUO = 347	--地焰火
CONST_SKILL_WUDUZHANGFA = 62	--五毒掌法
CONST_SKILL_WUDUDAOFA = 60	--五毒刀法
CONST_SKILL_JIUTIANKUANGLEI = 67	--九天狂雷
CONST_SKILL_EMEIJIANFA = 77	--峨嵋剑法
CONST_SKILL_EMEIZHANGFA = 79	--峨嵋掌法
CONST_SKILL_CUIYANDAOFA = 95	--翠烟刀法
CONST_SKILL_CUIYANSHUANGDAO = 97	--翠烟双刀
CONST_SKILL_GAIBANGZHANGFA = 116	--丐帮掌法
CONST_SKILL_GAIBANGBANGFA = 115	--丐帮棒法
CONST_SKILL_TIANRENMAOFA = 132	--天忍矛法
CONST_SKILL_TIANRENDAOFA = 131	--天忍刀法
CONST_SKILL_HUOLIANFENHUA = 136	--火莲焚华
CONST_SKILL_WUDANGQUANFA = 152	--武当拳法
CONST_SKILL_WUDANGJIANFA = 151	--武当剑法
CONST_SKILL_KUNLUNDAOFA = 167	--昆仑刀法
CONST_SKILL_KUNLUNJIANFA = 168	--昆仑剑法
CONST_SKILL_SHUFUZHOU = 392	--束缚咒
CONST_SKILL_QINGFENGFU = 171	--清风符

SKILLS = {
	[CONST_PARTY_SHAOLIN+1]={
		[10]={	
						CONST_SKILL_SHAOLINQUANFA,
						CONST_SKILL_SHAOLINGUNFA,
						CONST_SKILL_SHAOLINDAOFA
					},
		[30]={CONST_SKILL_LUOHANZHEN},
		[40]={CONST_SKILL_SHIZIHOU},
		[50]={
						CONST_SKILL_LONGZHAOHUZHUA,
						CONST_SKILL_HENGSAOLIUHE,
						CONST_SKILL_MOHEWULIANG},
		[60]={CONST_SKILL_YIJINJING}
	},
	[CONST_PARTY_TIANWANG+1] = {
		[10]={	
						CONST_SKILL_TIANWANGCHUIFA,
						CONST_SKILL_TIANWANGQIANGFA,
						CONST_SKILL_TIANWANGDAOFA
					},
		[30]={
						CONST_SKILL_POFENGZHAN,
						CONST_SKILL_YANGGUANSANDIE,
						CONST_SKILL_XINGYUNJUE
					},
		[40]={CONST_SKILL_DUANHUNCI},
		[50]={CONST_SKILL_JINZHONGZHAO},
		[60]={
						CONST_SKILL_WUXINZHAN,
						CONST_SKILL_XUEZHANBAFANG,
						CONST_SKILL_CHENGLONGJUE
					}
	},
	[CONST_PARTY_TANGMEN+1] = {
		[10]={
						CONST_SKILL_TANGMENANQI,
						CONST_SKILL_DIYANHUO
					},
		[30]={
						CONST_SKILL_ZHUIXINJIAN,
						CONST_SKILL_MANTIANHUAYU,
						CONST_SKILL_DUOHUNBIAO,
						CONST_SKILL_CHUANXINCI
					},
		[40]={CONST_SKILL_HANBINGCI},
		[50]={CONST_SKILL_LEIJISHU},
		[60]={
						CONST_SKILL_XIAOLIFEIDAO,
						CONST_SKILL_TIANLUODIWANG,
						CONST_SKILL_SANHUABIAO
					}
	},
	[CONST_PARTY_WUDU+1] = {
		[10]={
						CONST_SKILL_WUDUZHANGFA,
						CONST_SKILL_WUDUDAOFA,
						CONST_SKILL_JIUTIANKUANGLEI
					},
		[30]={
						CONST_SKILL_YOUMINGKULOU,
						CONST_SKILL_BAIDUCHUANXIN,
						CONST_SKILL_BINGLANXUANJING,
						CONST_SKILL_WUXINGGU
					},
		[40]={
						CONST_SKILL_CHUANYIPOJIA,
						CONST_SKILL_WANGUSHIXIN
					},
		[50]={CONST_SKILL_CHUANXINDUCI},
		[60]={	
						CONST_SKILL_TIANGANGDISHA,
						CONST_SKILL_ZHUHAQINGMING
					}
	},
	[CONST_PARTY_EMEI+1] = {
		[10]={
						CONST_SKILL_EMEIJIANFA,
						CONST_SKILL_EMEIZHANGFA
					},
		[30]={
						CONST_SKILL_TUICHUANGWANGYUE,
						CONST_SKILL_SIXIANGTONGGUI,
						CONST_SKILL_MENGDIE
					},
		[40]={CONST_SKILL_LIUSHUI},
		[50]={CONST_SKILL_FOXINCIYOU},
		[60]={
						CONST_SKILL_BUMIEBUJUE,
						CONST_SKILL_FOGUANGPUZHAO,
						CONST_SKILL_QINGXINFANCHANG
					}
	},
	[CONST_PARTY_CUIYAN+1] = {
		[10]={
						CONST_SKILL_CUIYANDAOFA,
						CONST_SKILL_CUIYANSHUANGDAO
					},
		[30]={
						CONST_SKILL_YUDALIHUA,
						CONST_SKILL_FUYUNSANXUE
					},
		[40]={CONST_SKILL_TUTIHANBING},
		[50]={CONST_SKILL_XUEYING},
		[60]={
						CONST_SKILL_MUYELIUXING,
						CONST_SKILL_BIHAICHAOSHENG
					}
	},
	[CONST_PARTY_GAIBANG+1] = {
		[10]={
						CONST_SKILL_GAIBANGZHANGFA,
						CONST_SKILL_GAIBANGBANGFA
					},
		[30]={
						CONST_SKILL_XIANGLONGZHANG,
						CONST_SKILL_DAGOUBANG
					},
		[40]={CONST_SKILL_HUABULIUSHOU},
		[50]={
						CONST_SKILL_KANGLONGYOUHUI,
						CONST_SKILL_BANGDAEGOU
					},
		[60]={CONST_SKILL_XIAOYAOGONG}
	},
	[CONST_PARTY_TIANREN+1] = {
		[10]={
						CONST_SKILL_TIANRENMAOFA,
						CONST_SKILL_TIANRENDAOFA,
						CONST_SKILL_HUOLIANFENHUA
					},
		[30]={		
						CONST_SKILL_LIEHONGQINGTIAN,
						CONST_SKILL_TUISHANTIANHAI,
						CONST_SKILL_FEIHONGWUJI
					},
		[40]={CONST_SKILL_BEISUQINGFENG},
		[50]={CONST_SKILL_LIMODUOPO},
		[60]={
						CONST_SKILL_TOUTIANHUANRI,
						CONST_SKILL_MOYANQISHA
					}
	},
	[CONST_PARTY_WUDANG+1] = {
		[10]={
						CONST_SKILL_WUDANGQUANFA,
						CONST_SKILL_WUDANGJIANFA
					},
		[30]={
						CONST_SKILL_BOJIERFU,
						ONST_SKILL_JIANFEIJINGTIAN
					},
		[40]={CONST_SKILL_TIYUNZONG},
		[50]={CONST_SKILL_ZUOWANGWUWO},
		[60]={CONST_SKILL_WUWOWUJIAN,CONST_SKILL_SANHUANTAOYUE}
	},
	[CONST_PARTY_KUNLUN+1] = {
		[10]={	
						CONST_SKILL_KUNLUNDAOFA,
						CONST_SKILL_KUNLUNJIANFA,
						CONST_SKILL_SHUFUZHOU,
						CONST_SKILL_QINGFENGFU
			},
		[30]={
						CONST_SKILL_YIQISANQING,
						CONST_SKILL_TIANJIXUNLEI,
						CONST_SKILL_BEIMINGDAOHAI,
						CONST_SKILL_TIANQINGDIZUO
					},
		[40]={
						CONST_SKILL_QIHANAOXUE,
						CONST_SKILL_QIXINFU
					},
		[50]={
						CONST_SKILL_KUANGFENGZHOUDIAN,
						CONST_SKILL_MIZONGHUANGYING
					},
		[60]={CONST_SKILL_WULEIZHENGFA}
	}
}
